col_screw = {
  # 'studyid': _, 
  # 'w1kessler6_i': _, 
  # 'kessler6_sqrt': _, 
  
  'abus_treat_non_queer': len(feat_eng_dict[k][1:]), 
  'abus_treat_sex_gender': len(feat_eng_dict[k][1:]), 
  # 'abusive_treatment': _, 
  # 'bad_neighbhd': _, 
  'childhd_bullying_non_queer': len(feat_eng_dict['childhd_bullying_non_queer'][1:]), 
  'childhd_bullying_sex_gender': len(feat_eng_dict['childhd_bullying_sex_gender'][1:]), 
  # 'chronic_strain': _, 
  'cohort': 'ohe', 
  'daily_discr_non_queer': len(feat_eng_dict[k][1:]), 
  'daily_discr_sex_gender': len(feat_eng_dict[k][1:]), 
  # 'disabled': _, 
  'gcendiv': d, 
  'gcenreg': o, 
  # 'geduc1': _, 
  'geduc2': d, 
  # 'geducation': _, 
  # 'gmilesaway2_ei_r': _, 
  # 'gurban_i': _, 
  'health_insurance': 'combine with q64', 
  'housing_disc_non_queer': len(feat_eng_dict[k][1:]), 
  'housing_disc_sex_gender': len(feat_eng_dict[k][1:]), 
  # 'outness': _, 
  'screen_race': 'check with other race stuff', 
  'serious_health_cond': _, 
  'stress_past_year_crime': _, 
  'stress_past_year_gen': _, 
  'stress_past_year_interpersonal': _, 
  'stress_past_year_non_queer': _, 
  'stress_past_year_sex_gender': _, 
  'stress_past_year_work': _, 
  'suicidality': _, 
  'w1ace_emo_i': _, 
  'w1ace_i': _, 
  'w1ace_inc_i': _, 
  'w1ace_ipv_i': _, 
  'w1ace_men_i': _, 
  'w1ace_phy_i': _, 
  'w1ace_sep_i': _, 
  'w1ace_sex_i': _, 
  'w1ace_sub_i': _, 
  'w1age': _, 
  'w1auditc_i': _, 
  'w1childgnc_i': _, 
  'w1connectedness_i': _, 
  'w1conversion': _, 
  'w1conversionhc': _, 
  'w1conversionrel': _, 
  'w1dudit_i': _, 
  'w1everyday_i': _, 
  'w1feltstigma_i': _, 
  'w1gender': _, 
  'w1hcthreat_i': _, 
  'w1hinc_i': _, 
  'w1idcentral_i': _, 
  'w1internalized_i': _, 
  'w1lifesat_i': _, 
  'w1meim_i': _, 
  'w1pinc_i': _, 
  'w1poverty_i_ei': _, 
  'w1povertycat_i_ei': _, 
  'w1q01_ei': _, 
  'w1q03_ei': _, 
  'w1q119_ei': _, 
  'w1q136_7_ei': _, 
  'w1q139_7_ei': _, 
  'w1q140_ei': _, 
  'w1q141_7_ei': _, 
  'w1q143_7_ei': _, 
  'w1q145_7_ei': _, 
  'w1q162_ei': _, 
  'w1q163_7_ei': _, 
  'w1q166_ei': _, 
  'w1q167_ei': _, 
  'w1q168_ei': _, 
  'w1q169_ei': _, 
  'w1q171_1_ei': _, 
  'w1q171_2_ei': _, 
  'w1q171_3_ei': _, 
  'w1q171_4_ei': _, 
  'w1q171_5_ei': _, 
  'w1q171_6_ei': _, 
  'w1q171_7_ei': _, 
  'w1q171_8_ei': _, 
  'w1q171_9_ei': _, 
  'w1q175_ei': _, 
  'w1q179_ei_r_relig_christ': _, 
  'w1q179_ei_r_relig_other': _, 
  'w1q180_ei_r_relig_christ': _, 
  'w1q180_ei_r_relig_other': _, 
  'w1q181_ei_r': _, 
  'w1q30_1_ei': _, 
  'w1q30_2_ei': _, 
  'w1q30_3_ei': _, 
  'w1q30_4_ei': _, 
  'w1q30_5_ei': _, 
  'w1q32_ei': _, 
  'w1q33_ei': _, 
  'w1q34_ei': _, 
  'w1q35_ei': _, 
  'w1q36_ei': _, 
  'w1q37_ei': _, 
  'w1q38_ei': _, 
  'w1q52_ei': _, 
  'w1q64_1_ei': _, 
  'w1q65_ei': _, 
  'w1q69_ei': _, 
  'w1q72_ei': _, 
  'w1q74_21_ei': _, 
  'w1q74_22_ei': _, 
  'w1q74_23_ei': _, 
  'w1q78_ei': _, 
  'w1q79_ei': _, 
  'w1q89_ei': _, 
  'w1race': _, 
  'w1sex': _, 
  'w1sex_gender': _, 
  'w1sexminid': _, 
  'w1sexualid': _, 
  'w1socialwb_i': _, 
  'w1socsupport_fam_i': _, 
  'w1socsupport_fr_i': _, 
  'w1socsupport_i': _, 
  'w1socsupport_so_i': _, 
  'w1survey_yr': _, 
  'w1weight_full': _, 
  'waveparticipated': _, 
  'work_disc_non_queer': _, 
  'work_disc_sex_gender': _, 
  'work_neg_outcomes': _,
}
